# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/StoreApp/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
 
steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Sonar Cloud'
      organization: '210503-reston-net'
      scannerMode: 'MSBuild'
      projectKey: '210503-Reston-NET_Fang-Phoebe-P1'
      projectName: 'Fang-Phoebe-P1'
      extraProperties: 'sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/coverage.opencover.xml'

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: $(solution)
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      projects: $(solution)

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true "/p:CoverletOutputFormat=\"opencover,Cobertura\"" /p:excludebyfile=\"**/DL/Migrations/*.cs\"'
      publishTestResults: true  

  - task: PublishCodeCoverageResults@1
    displayName: Publish Code Coverage Report
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'
      reportDirectory: '$(Build.SourcesDirectory)/StoreApp/StoreTests/' 

  - task: SonarCloudAnalyze@1
    displayName: Run Code Analysis
  - task: SonarCloudPublish@1
    displayName: Publish Code Analysis
 
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: 'publish'
      publishWebProjects: false
      zipAfterPublish: true
      projects: '**/StoreApp/WebUI/*.csproj'
      
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure service'
      appType: 'webApp'
      WebAppName: 'bbtapps'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

